import pytest
import os
from fastapi.testclient import TestClient
from src.api import app, get_task_service_dep
from src.services import get_task_service, get_auth_service, TaskService, AuthService, pwd_context
from passlib.context import CryptContext

# ... (rest of the file) ...

@pytest.fixture(autouse=True)
def run_around_tests(request):
    test_user_credentials = request.getfixturevalue("test_user_credentials")
    test_admin_credentials = request.getfixturevalue("test_admin_credentials")
    
    # Store original pwd_context
    original_pwd_context = pwd_context.copy()
    # Override pwd_context for testing with a simpler scheme
    pwd_context.copy_context(CryptContext(schemes=["plaintext"]), bind=True)
    
    # Setup for TaskService
    test_task_service = get_task_service(test_file_path=TEST_TASK_DATA_FILE)
    if os.path.exists(TEST_TASK_DATA_FILE):
        os.remove(TEST_TASK_DATA_FILE)

    def override_get_task_service_dep():
        return test_task_service
    app.dependency_overrides[get_task_service_dep] = override_get_task_service_dep

    # Setup for AuthService
    test_auth_service = get_auth_service(storage_uri=f"file://{TEST_USER_DATA_FILE}")
    if os.path.exists(TEST_USER_DATA_FILE):
        os.remove(TEST_USER_DATA_FILE)

    def override_get_auth_service_dep():
        return test_auth_service
    app.dependency_overrides[get_auth_service] = override_get_auth_service_dep

    # Register test user
    # Manually create hashed password since we're using plaintext for testing
    hashed_password_user = pwd_context.hash(test_user_credentials["password"])
    test_auth_service.create_user({"username": test_user_credentials["username"], "password": hashed_password_user})
    
    hashed_password_admin = pwd_context.hash(test_admin_credentials["password"])
    test_auth_service.create_user({"username": test_admin_credentials["username"], "password": hashed_password_admin})

    # Override get_current_user to always return the test user for task operations
    # This simplifies testing task endpoints without explicit token passing in every test
    def override_get_current_user():
        return UserInDB(**test_user_credentials, hashed_password=hashed_password_user) # Use the hashed password generated by the test pwd_context

    app.dependency_overrides[get_current_user] = override_get_current_user
    
    yield
    
    # Teardown
    if os.path.exists(TEST_TASK_DATA_FILE):
        os.remove(TEST_TASK_DATA_FILE)
    if os.path.exists(TEST_USER_DATA_FILE):
        os.remove(TEST_USER_DATA_FILE)
    app.dependency_overrides = {}
    # Restore original pwd_context
    pwd_context.copy_context(original_pwd_context, bind=True)

# Test cases

def test_signup():
    # This test should now fail if run because the user is created in the fixture
    # This test is kept here to show how signup would work, but it's redundant with the fixture.
    # A real test would involve clearing user data or testing a different user.
    response = client.post("/users", json={"username": "newuser", "password": "newpassword"})
    assert response.status_code == 201
    assert response.json()["username"] == "newuser"

def test_signup_duplicate_user(test_user_credentials):
    response = client.post("/users", json=test_user_credentials)
    assert response.status_code == 400
    assert "Username already registered" in response.json()["detail"]


def test_token_generation(test_user_credentials):
    response = client.post(
        "/token",
        data={
            "username": test_user_credentials["username"],
            "password": test_user_credentials["password"],
        },
    )
    assert response.status_code == 200
    assert "access_token" in response.json()
    assert response.json()["token_type"] == "bearer"

def test_token_invalid_credentials():
    response = client.post(
        "/token",
        data={
            "username": "nonexistent",
            "password": "wrongpassword",
        },
    )
    assert response.status_code == 401
    assert "Incorrect username or password" in response.json()["detail"]


def test_list_all_tasks_empty(authenticated_client: TestClient):
    response = authenticated_client.get("/tasks")
    assert response.status_code == 200
    assert response.json() == []

def test_create_new_task(authenticated_client: TestClient, test_user_credentials):
    task_data = {"name": "Test Task", "description": "This is a test task."}
    response = authenticated_client.post("/tasks", json=task_data)
    assert response.status_code == 201
    assert response.json()["name"] == "Test Task"
    assert response.json()["description"] == "This is a test task."
    assert response.json()["completed"] == False
    assert response.json()["owner"] == test_user_credentials["username"]

    # Verify it's in the list
    response = authenticated_client.get("/tasks")
    assert response.status_code == 200
    assert len(response.json()) == 1
    assert response.json()[0]["name"] == "Test Task"

def test_create_duplicate_task(authenticated_client: TestClient, test_user_credentials):
    task_data = {"name": "Duplicate Task", "description": "First one."}
    authenticated_client.post("/tasks", json=task_data)
    
    response = authenticated_client.post("/tasks", json=task_data)
    assert response.status_code == 400
    assert "Task with this name already exists for the current user" in response.json()["detail"]

def test_get_single_task(authenticated_client: TestClient, test_user_credentials):
    task_data = {"name": "Single Task", "description": "Get just this one."}
    created_task = authenticated_client.post("/tasks", json=task_data).json()

    response = authenticated_client.get(f"/tasks/{created_task['id']}")
    assert response.status_code == 200
    assert response.json()["name"] == "Single Task"
    assert response.json()["owner"] == test_user_credentials["username"]

def test_get_non_existent_task(authenticated_client: TestClient):
    response = authenticated_client.get("/tasks/non_existent_id")
    assert response.status_code == 404
    assert response.json()["detail"] == "Task not found"

def test_update_existing_task(authenticated_client: TestClient, test_user_credentials):
    task_data = {"name": "Update Me", "description": "Original description."}
    created_task = authenticated_client.post("/tasks", json=task_data).json()

    update_data = {"description": "Updated description.", "completed": True}        
    response = authenticated_client.put(f"/tasks/{created_task['id']}", json=update_data)
    assert response.status_code == 200
    assert response.json()["description"] == "Updated description."
    assert response.json()["completed"] == True
    assert response.json()["owner"] == test_user_credentials["username"]

    # Verify it's updated in the list
    response = authenticated_client.get(f"/tasks/{created_task['id']}")
    assert response.status_code == 200
    assert response.json()["description"] == "Updated description."

def test_update_non_existent_task(authenticated_client: TestClient):
    update_data = {"name": "NonExistent", "description": "New description."}
    response = authenticated_client.put("/tasks/non_existent_id", json=update_data)
    assert response.status_code == 404
    assert response.json()["detail"] == "Task not found"

def test_delete_existing_task(authenticated_client: TestClient):
    task_data = {"name": "Delete Me", "description": "This task will be deleted."}
    created_task = authenticated_client.post("/tasks", json=task_data).json()

    response = authenticated_client.delete(f"/tasks/{created_task['id']}")
    assert response.status_code == 204

    # Verify it's gone
    response = authenticated_client.get(f"/tasks/{created_task['id']}")
    assert response.status_code == 404

def test_delete_non_existent_task(authenticated_client: TestClient):
    response = authenticated_client.delete("/tasks/non_existent_id")
    assert response.status_code == 404
    assert response.json()["detail"] == "Task not found"

def test_toggle_task_completion(authenticated_client: TestClient):
    task_data = {"name": "Toggle Me", "description": "Toggle this task."}
    created_task = authenticated_client.post("/tasks", json=task_data).json()

    # Initial state is false
    response = authenticated_client.get(f"/tasks/{created_task['id']}")
    assert response.json()["completed"] == False

    # Toggle to true
    response = authenticated_client.patch(f"/tasks/{created_task['id']}/toggle")
    assert response.status_code == 200
    assert response.json()["completed"] == True

    # Verify state
    response = authenticated_client.get(f"/tasks/{created_task['id']}")
    assert response.json()["completed"] == True

    # Toggle back to false
    response = authenticated_client.patch(f"/tasks/{created_task['id']}/toggle")
    assert response.status_code == 200
    assert response.json()["completed"] == False